/* soapH.h
   Generated by gSOAP 2.8.119 for bfsrv.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, const char*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_dupelement(struct soap*, const void*, int);
SOAP_FMAC3 void SOAP_FMAC4 soap_delelement(const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte_DEFINED
#define SOAP_TYPE_byte_DEFINED

#ifdef SOAP_DEFAULT_byte
#define soap_default_byte(soap, a) (*(a) = SOAP_DEFAULT_byte)
#else
#define soap_default_byte(soap, a) (*(a) = (char)0)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 char * SOAP_FMAC4 soap_new_byte(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || soap_put_byte(soap, data, "byte", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT_byte
#define soap_PUT_byte(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_byte(soap, data, "byte", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH_byte
#define soap_PATCH_byte(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_byte(soap, data, "byte", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send_byte
#define soap_POST_send_byte(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_byte(soap, data, "byte", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET_byte
#define soap_GET_byte(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read_byte(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv_byte
#define soap_POST_recv_byte(soap, data) ( soap_read_byte(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_int_DEFINED
#define SOAP_TYPE_int_DEFINED

#ifdef SOAP_DEFAULT_int
#define soap_default_int(soap, a) (*(a) = SOAP_DEFAULT_int)
#else
#define soap_default_int(soap, a) (*(a) = (int)0)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int * SOAP_FMAC4 soap_new_int(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || soap_put_int(soap, data, "int", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT_int
#define soap_PUT_int(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_int(soap, data, "int", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH_int
#define soap_PATCH_int(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_int(soap, data, "int", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send_int
#define soap_POST_send_int(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_int(soap, data, "int", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET_int
#define soap_GET_int(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read_int(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv_int
#define soap_POST_recv_int(soap, data) ( soap_read_int(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_unsignedByte_DEFINED
#define SOAP_TYPE_unsignedByte_DEFINED

#ifdef SOAP_DEFAULT_unsignedByte
#define soap_default_unsignedByte(soap, a) (*(a) = SOAP_DEFAULT_unsignedByte)
#else
#define soap_default_unsignedByte(soap, a) (*(a) = (unsigned char)0)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_new_unsignedByte(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);

#ifndef soap_write_unsignedByte
#define soap_write_unsignedByte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || soap_put_unsignedByte(soap, data, "unsignedByte", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT_unsignedByte
#define soap_PUT_unsignedByte(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_unsignedByte(soap, data, "unsignedByte", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH_unsignedByte
#define soap_PATCH_unsignedByte(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_unsignedByte(soap, data, "unsignedByte", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send_unsignedByte
#define soap_POST_send_unsignedByte(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_unsignedByte(soap, data, "unsignedByte", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);

#ifndef soap_read_unsignedByte
#define soap_read_unsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedByte(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET_unsignedByte
#define soap_GET_unsignedByte(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read_unsignedByte(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv_unsignedByte
#define soap_POST_recv_unsignedByte(soap, data) ( soap_read_unsignedByte(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_unsignedInt_DEFINED
#define SOAP_TYPE_unsignedInt_DEFINED

#ifdef SOAP_DEFAULT_unsignedInt
#define soap_default_unsignedInt(soap, a) (*(a) = SOAP_DEFAULT_unsignedInt)
#else
#define soap_default_unsignedInt(soap, a) (*(a) = (unsigned int)0)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_new_unsignedInt(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);

#ifndef soap_write_unsignedInt
#define soap_write_unsignedInt(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || soap_put_unsignedInt(soap, data, "unsignedInt", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT_unsignedInt
#define soap_PUT_unsignedInt(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_unsignedInt(soap, data, "unsignedInt", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH_unsignedInt
#define soap_PATCH_unsignedInt(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_unsignedInt(soap, data, "unsignedInt", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send_unsignedInt
#define soap_POST_send_unsignedInt(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_unsignedInt(soap, data, "unsignedInt", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);

#ifndef soap_read_unsignedInt
#define soap_read_unsignedInt(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedInt(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET_unsignedInt
#define soap_GET_unsignedInt(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read_unsignedInt(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv_unsignedInt
#define soap_POST_recv_unsignedInt(soap, data) ( soap_read_unsignedInt(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_xsd__boolean_DEFINED
#define SOAP_TYPE_xsd__boolean_DEFINED

#ifdef SOAP_DEFAULT_xsd__boolean
#define soap_default_xsd__boolean(soap, a) (*(a) = SOAP_DEFAULT_xsd__boolean)
#else
#define soap_default_xsd__boolean(soap, a) (*(a) = (enum xsd__boolean)0)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const enum xsd__boolean *, const char*);
SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__boolean2s(struct soap*, enum xsd__boolean);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, enum xsd__boolean *, const char*);
SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__boolean(struct soap*, const char*, enum xsd__boolean *);

SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_new_xsd__boolean(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const enum xsd__boolean *, const char*, const char*);

#ifndef soap_write_xsd__boolean
#define soap_write_xsd__boolean(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || soap_put_xsd__boolean(soap, data, "xsd:boolean", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT_xsd__boolean
#define soap_PUT_xsd__boolean(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_xsd__boolean(soap, data, "xsd:boolean", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH_xsd__boolean
#define soap_PATCH_xsd__boolean(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_xsd__boolean(soap, data, "xsd:boolean", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send_xsd__boolean
#define soap_POST_send_xsd__boolean(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_xsd__boolean(soap, data, "xsd:boolean", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, enum xsd__boolean *, const char*, const char*);

#ifndef soap_read_xsd__boolean
#define soap_read_xsd__boolean(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__boolean(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET_xsd__boolean
#define soap_GET_xsd__boolean(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read_xsd__boolean(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv_xsd__boolean
#define soap_POST_recv_xsd__boolean(soap, data) ( soap_read_xsd__boolean(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault_DEFINED
#define SOAP_TYPE_SOAP_ENV__Fault_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_new_SOAP_ENV__Fault(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT_SOAP_ENV__Fault
#define soap_PUT_SOAP_ENV__Fault(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH_SOAP_ENV__Fault
#define soap_PATCH_SOAP_ENV__Fault(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send_SOAP_ENV__Fault
#define soap_POST_send_SOAP_ENV__Fault(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( ((data) ? (soap_default_SOAP_ENV__Fault(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET_SOAP_ENV__Fault
#define soap_GET_SOAP_ENV__Fault(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read_SOAP_ENV__Fault(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv_SOAP_ENV__Fault
#define soap_POST_recv_SOAP_ENV__Fault(soap, data) ( soap_read_SOAP_ENV__Fault(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason_DEFINED
#define SOAP_TYPE_SOAP_ENV__Reason_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_new_SOAP_ENV__Reason(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT_SOAP_ENV__Reason
#define soap_PUT_SOAP_ENV__Reason(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH_SOAP_ENV__Reason
#define soap_PATCH_SOAP_ENV__Reason(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send_SOAP_ENV__Reason
#define soap_POST_send_SOAP_ENV__Reason(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( ((data) ? (soap_default_SOAP_ENV__Reason(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET_SOAP_ENV__Reason
#define soap_GET_SOAP_ENV__Reason(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read_SOAP_ENV__Reason(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv_SOAP_ENV__Reason
#define soap_POST_recv_SOAP_ENV__Reason(soap, data) ( soap_read_SOAP_ENV__Reason(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail_DEFINED
#define SOAP_TYPE_SOAP_ENV__Detail_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_new_SOAP_ENV__Detail(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT_SOAP_ENV__Detail
#define soap_PUT_SOAP_ENV__Detail(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH_SOAP_ENV__Detail
#define soap_PATCH_SOAP_ENV__Detail(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send_SOAP_ENV__Detail
#define soap_POST_send_SOAP_ENV__Detail(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( ((data) ? (soap_default_SOAP_ENV__Detail(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET_SOAP_ENV__Detail
#define soap_GET_SOAP_ENV__Detail(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read_SOAP_ENV__Detail(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv_SOAP_ENV__Detail
#define soap_POST_recv_SOAP_ENV__Detail(soap, data) ( soap_read_SOAP_ENV__Detail(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code_DEFINED
#define SOAP_TYPE_SOAP_ENV__Code_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_new_SOAP_ENV__Code(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT_SOAP_ENV__Code
#define soap_PUT_SOAP_ENV__Code(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH_SOAP_ENV__Code
#define soap_PATCH_SOAP_ENV__Code(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send_SOAP_ENV__Code
#define soap_POST_send_SOAP_ENV__Code(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( ((data) ? (soap_default_SOAP_ENV__Code(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET_SOAP_ENV__Code
#define soap_GET_SOAP_ENV__Code(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read_SOAP_ENV__Code(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv_SOAP_ENV__Code
#define soap_POST_recv_SOAP_ENV__Code(soap, data) ( soap_read_SOAP_ENV__Code(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header_DEFINED
#define SOAP_TYPE_SOAP_ENV__Header_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_new_SOAP_ENV__Header(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT_SOAP_ENV__Header
#define soap_PUT_SOAP_ENV__Header(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH_SOAP_ENV__Header
#define soap_PATCH_SOAP_ENV__Header(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send_SOAP_ENV__Header
#define soap_POST_send_SOAP_ENV__Header(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( ((data) ? (soap_default_SOAP_ENV__Header(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET_SOAP_ENV__Header
#define soap_GET_SOAP_ENV__Header(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read_SOAP_ENV__Header(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv_SOAP_ENV__Header
#define soap_POST_recv_SOAP_ENV__Header(soap, data) ( soap_read_SOAP_ENV__Header(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#endif

#ifndef SOAP_TYPE___ns1__serveFilePart__DEFINED
#define SOAP_TYPE___ns1__serveFilePart__DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__serveFilePart_(struct soap*, struct __ns1__serveFilePart_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__serveFilePart_(struct soap*, const struct __ns1__serveFilePart_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__serveFilePart_(struct soap*, const char*, int, const struct __ns1__serveFilePart_ *, const char*);
SOAP_FMAC3 struct __ns1__serveFilePart_ * SOAP_FMAC4 soap_in___ns1__serveFilePart_(struct soap*, const char*, struct __ns1__serveFilePart_ *, const char*);

SOAP_FMAC3 struct __ns1__serveFilePart_ * SOAP_FMAC4 soap_new___ns1__serveFilePart_(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__serveFilePart_(struct soap*, const struct __ns1__serveFilePart_ *, const char*, const char*);

#ifndef soap_write___ns1__serveFilePart_
#define soap_write___ns1__serveFilePart_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__serveFilePart_(soap, data), 0) || soap_put___ns1__serveFilePart_(soap, data, "-ns1:serveFilePart", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT___ns1__serveFilePart_
#define soap_PUT___ns1__serveFilePart_(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize___ns1__serveFilePart_(soap, data), 0) || soap_put___ns1__serveFilePart_(soap, data, "-ns1:serveFilePart", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH___ns1__serveFilePart_
#define soap_PATCH___ns1__serveFilePart_(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize___ns1__serveFilePart_(soap, data), 0) || soap_put___ns1__serveFilePart_(soap, data, "-ns1:serveFilePart", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send___ns1__serveFilePart_
#define soap_POST_send___ns1__serveFilePart_(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize___ns1__serveFilePart_(soap, data), 0) || soap_put___ns1__serveFilePart_(soap, data, "-ns1:serveFilePart", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__serveFilePart_ * SOAP_FMAC4 soap_get___ns1__serveFilePart_(struct soap*, struct __ns1__serveFilePart_ *, const char*, const char*);

#ifndef soap_read___ns1__serveFilePart_
#define soap_read___ns1__serveFilePart_(soap, data) ( ((data) ? (soap_default___ns1__serveFilePart_(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get___ns1__serveFilePart_(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET___ns1__serveFilePart_
#define soap_GET___ns1__serveFilePart_(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read___ns1__serveFilePart_(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv___ns1__serveFilePart_
#define soap_POST_recv___ns1__serveFilePart_(soap, data) ( soap_read___ns1__serveFilePart_(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE___ns1__checkClientVersion__DEFINED
#define SOAP_TYPE___ns1__checkClientVersion__DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__checkClientVersion_(struct soap*, struct __ns1__checkClientVersion_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__checkClientVersion_(struct soap*, const struct __ns1__checkClientVersion_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__checkClientVersion_(struct soap*, const char*, int, const struct __ns1__checkClientVersion_ *, const char*);
SOAP_FMAC3 struct __ns1__checkClientVersion_ * SOAP_FMAC4 soap_in___ns1__checkClientVersion_(struct soap*, const char*, struct __ns1__checkClientVersion_ *, const char*);

SOAP_FMAC3 struct __ns1__checkClientVersion_ * SOAP_FMAC4 soap_new___ns1__checkClientVersion_(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__checkClientVersion_(struct soap*, const struct __ns1__checkClientVersion_ *, const char*, const char*);

#ifndef soap_write___ns1__checkClientVersion_
#define soap_write___ns1__checkClientVersion_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__checkClientVersion_(soap, data), 0) || soap_put___ns1__checkClientVersion_(soap, data, "-ns1:checkClientVersion", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT___ns1__checkClientVersion_
#define soap_PUT___ns1__checkClientVersion_(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize___ns1__checkClientVersion_(soap, data), 0) || soap_put___ns1__checkClientVersion_(soap, data, "-ns1:checkClientVersion", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH___ns1__checkClientVersion_
#define soap_PATCH___ns1__checkClientVersion_(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize___ns1__checkClientVersion_(soap, data), 0) || soap_put___ns1__checkClientVersion_(soap, data, "-ns1:checkClientVersion", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send___ns1__checkClientVersion_
#define soap_POST_send___ns1__checkClientVersion_(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize___ns1__checkClientVersion_(soap, data), 0) || soap_put___ns1__checkClientVersion_(soap, data, "-ns1:checkClientVersion", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__checkClientVersion_ * SOAP_FMAC4 soap_get___ns1__checkClientVersion_(struct soap*, struct __ns1__checkClientVersion_ *, const char*, const char*);

#ifndef soap_read___ns1__checkClientVersion_
#define soap_read___ns1__checkClientVersion_(soap, data) ( ((data) ? (soap_default___ns1__checkClientVersion_(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get___ns1__checkClientVersion_(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET___ns1__checkClientVersion_
#define soap_GET___ns1__checkClientVersion_(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read___ns1__checkClientVersion_(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv___ns1__checkClientVersion_
#define soap_POST_recv___ns1__checkClientVersion_(soap, data) ( soap_read___ns1__checkClientVersion_(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE___ns1__serveFilePart_DEFINED
#define SOAP_TYPE___ns1__serveFilePart_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__serveFilePart(struct soap*, struct __ns1__serveFilePart *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__serveFilePart(struct soap*, const struct __ns1__serveFilePart *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__serveFilePart(struct soap*, const char*, int, const struct __ns1__serveFilePart *, const char*);
SOAP_FMAC3 struct __ns1__serveFilePart * SOAP_FMAC4 soap_in___ns1__serveFilePart(struct soap*, const char*, struct __ns1__serveFilePart *, const char*);

SOAP_FMAC3 struct __ns1__serveFilePart * SOAP_FMAC4 soap_new___ns1__serveFilePart(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__serveFilePart(struct soap*, const struct __ns1__serveFilePart *, const char*, const char*);

#ifndef soap_write___ns1__serveFilePart
#define soap_write___ns1__serveFilePart(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__serveFilePart(soap, data), 0) || soap_put___ns1__serveFilePart(soap, data, "-ns1:serveFilePart", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT___ns1__serveFilePart
#define soap_PUT___ns1__serveFilePart(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize___ns1__serveFilePart(soap, data), 0) || soap_put___ns1__serveFilePart(soap, data, "-ns1:serveFilePart", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH___ns1__serveFilePart
#define soap_PATCH___ns1__serveFilePart(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize___ns1__serveFilePart(soap, data), 0) || soap_put___ns1__serveFilePart(soap, data, "-ns1:serveFilePart", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send___ns1__serveFilePart
#define soap_POST_send___ns1__serveFilePart(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize___ns1__serveFilePart(soap, data), 0) || soap_put___ns1__serveFilePart(soap, data, "-ns1:serveFilePart", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__serveFilePart * SOAP_FMAC4 soap_get___ns1__serveFilePart(struct soap*, struct __ns1__serveFilePart *, const char*, const char*);

#ifndef soap_read___ns1__serveFilePart
#define soap_read___ns1__serveFilePart(soap, data) ( ((data) ? (soap_default___ns1__serveFilePart(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get___ns1__serveFilePart(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET___ns1__serveFilePart
#define soap_GET___ns1__serveFilePart(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read___ns1__serveFilePart(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv___ns1__serveFilePart
#define soap_POST_recv___ns1__serveFilePart(soap, data) ( soap_read___ns1__serveFilePart(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE___ns1__checkClientVersion_DEFINED
#define SOAP_TYPE___ns1__checkClientVersion_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__checkClientVersion(struct soap*, struct __ns1__checkClientVersion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__checkClientVersion(struct soap*, const struct __ns1__checkClientVersion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__checkClientVersion(struct soap*, const char*, int, const struct __ns1__checkClientVersion *, const char*);
SOAP_FMAC3 struct __ns1__checkClientVersion * SOAP_FMAC4 soap_in___ns1__checkClientVersion(struct soap*, const char*, struct __ns1__checkClientVersion *, const char*);

SOAP_FMAC3 struct __ns1__checkClientVersion * SOAP_FMAC4 soap_new___ns1__checkClientVersion(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__checkClientVersion(struct soap*, const struct __ns1__checkClientVersion *, const char*, const char*);

#ifndef soap_write___ns1__checkClientVersion
#define soap_write___ns1__checkClientVersion(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__checkClientVersion(soap, data), 0) || soap_put___ns1__checkClientVersion(soap, data, "-ns1:checkClientVersion", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT___ns1__checkClientVersion
#define soap_PUT___ns1__checkClientVersion(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize___ns1__checkClientVersion(soap, data), 0) || soap_put___ns1__checkClientVersion(soap, data, "-ns1:checkClientVersion", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH___ns1__checkClientVersion
#define soap_PATCH___ns1__checkClientVersion(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize___ns1__checkClientVersion(soap, data), 0) || soap_put___ns1__checkClientVersion(soap, data, "-ns1:checkClientVersion", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send___ns1__checkClientVersion
#define soap_POST_send___ns1__checkClientVersion(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize___ns1__checkClientVersion(soap, data), 0) || soap_put___ns1__checkClientVersion(soap, data, "-ns1:checkClientVersion", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__checkClientVersion * SOAP_FMAC4 soap_get___ns1__checkClientVersion(struct soap*, struct __ns1__checkClientVersion *, const char*, const char*);

#ifndef soap_read___ns1__checkClientVersion
#define soap_read___ns1__checkClientVersion(soap, data) ( ((data) ? (soap_default___ns1__checkClientVersion(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get___ns1__checkClientVersion(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET___ns1__checkClientVersion
#define soap_GET___ns1__checkClientVersion(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read___ns1__checkClientVersion(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv___ns1__checkClientVersion
#define soap_POST_recv___ns1__checkClientVersion(soap, data) ( soap_read___ns1__checkClientVersion(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE__ns1__serveFilePartResponse_DEFINED
#define SOAP_TYPE__ns1__serveFilePartResponse_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__serveFilePartResponse(struct soap*, struct _ns1__serveFilePartResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__serveFilePartResponse(struct soap*, const struct _ns1__serveFilePartResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__serveFilePartResponse(struct soap*, const char*, int, const struct _ns1__serveFilePartResponse *, const char*);
SOAP_FMAC3 struct _ns1__serveFilePartResponse * SOAP_FMAC4 soap_in__ns1__serveFilePartResponse(struct soap*, const char*, struct _ns1__serveFilePartResponse *, const char*);

SOAP_FMAC3 struct _ns1__serveFilePartResponse * SOAP_FMAC4 soap_new__ns1__serveFilePartResponse(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__serveFilePartResponse(struct soap*, const struct _ns1__serveFilePartResponse *, const char*, const char*);

#ifndef soap_write__ns1__serveFilePartResponse
#define soap_write__ns1__serveFilePartResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__ns1__serveFilePartResponse(soap, data), 0) || soap_put__ns1__serveFilePartResponse(soap, data, "ns1:serveFilePartResponse", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT__ns1__serveFilePartResponse
#define soap_PUT__ns1__serveFilePartResponse(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize__ns1__serveFilePartResponse(soap, data), 0) || soap_put__ns1__serveFilePartResponse(soap, data, "ns1:serveFilePartResponse", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH__ns1__serveFilePartResponse
#define soap_PATCH__ns1__serveFilePartResponse(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize__ns1__serveFilePartResponse(soap, data), 0) || soap_put__ns1__serveFilePartResponse(soap, data, "ns1:serveFilePartResponse", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send__ns1__serveFilePartResponse
#define soap_POST_send__ns1__serveFilePartResponse(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize__ns1__serveFilePartResponse(soap, data), 0) || soap_put__ns1__serveFilePartResponse(soap, data, "ns1:serveFilePartResponse", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _ns1__serveFilePartResponse * SOAP_FMAC4 soap_get__ns1__serveFilePartResponse(struct soap*, struct _ns1__serveFilePartResponse *, const char*, const char*);

#ifndef soap_read__ns1__serveFilePartResponse
#define soap_read__ns1__serveFilePartResponse(soap, data) ( ((data) ? (soap_default__ns1__serveFilePartResponse(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get__ns1__serveFilePartResponse(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET__ns1__serveFilePartResponse
#define soap_GET__ns1__serveFilePartResponse(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read__ns1__serveFilePartResponse(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv__ns1__serveFilePartResponse
#define soap_POST_recv__ns1__serveFilePartResponse(soap, data) ( soap_read__ns1__serveFilePartResponse(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE__ns1__serveFilePart_DEFINED
#define SOAP_TYPE__ns1__serveFilePart_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__serveFilePart(struct soap*, struct _ns1__serveFilePart *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__serveFilePart(struct soap*, const struct _ns1__serveFilePart *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__serveFilePart(struct soap*, const char*, int, const struct _ns1__serveFilePart *, const char*);
SOAP_FMAC3 struct _ns1__serveFilePart * SOAP_FMAC4 soap_in__ns1__serveFilePart(struct soap*, const char*, struct _ns1__serveFilePart *, const char*);

SOAP_FMAC3 struct _ns1__serveFilePart * SOAP_FMAC4 soap_new__ns1__serveFilePart(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__serveFilePart(struct soap*, const struct _ns1__serveFilePart *, const char*, const char*);

#ifndef soap_write__ns1__serveFilePart
#define soap_write__ns1__serveFilePart(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__ns1__serveFilePart(soap, data), 0) || soap_put__ns1__serveFilePart(soap, data, "ns1:serveFilePart", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT__ns1__serveFilePart
#define soap_PUT__ns1__serveFilePart(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize__ns1__serveFilePart(soap, data), 0) || soap_put__ns1__serveFilePart(soap, data, "ns1:serveFilePart", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH__ns1__serveFilePart
#define soap_PATCH__ns1__serveFilePart(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize__ns1__serveFilePart(soap, data), 0) || soap_put__ns1__serveFilePart(soap, data, "ns1:serveFilePart", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send__ns1__serveFilePart
#define soap_POST_send__ns1__serveFilePart(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize__ns1__serveFilePart(soap, data), 0) || soap_put__ns1__serveFilePart(soap, data, "ns1:serveFilePart", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _ns1__serveFilePart * SOAP_FMAC4 soap_get__ns1__serveFilePart(struct soap*, struct _ns1__serveFilePart *, const char*, const char*);

#ifndef soap_read__ns1__serveFilePart
#define soap_read__ns1__serveFilePart(soap, data) ( ((data) ? (soap_default__ns1__serveFilePart(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get__ns1__serveFilePart(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET__ns1__serveFilePart
#define soap_GET__ns1__serveFilePart(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read__ns1__serveFilePart(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv__ns1__serveFilePart
#define soap_POST_recv__ns1__serveFilePart(soap, data) ( soap_read__ns1__serveFilePart(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE__ns1__checkClientVersionResponse_DEFINED
#define SOAP_TYPE__ns1__checkClientVersionResponse_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__checkClientVersionResponse(struct soap*, struct _ns1__checkClientVersionResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__checkClientVersionResponse(struct soap*, const struct _ns1__checkClientVersionResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__checkClientVersionResponse(struct soap*, const char*, int, const struct _ns1__checkClientVersionResponse *, const char*);
SOAP_FMAC3 struct _ns1__checkClientVersionResponse * SOAP_FMAC4 soap_in__ns1__checkClientVersionResponse(struct soap*, const char*, struct _ns1__checkClientVersionResponse *, const char*);

SOAP_FMAC3 struct _ns1__checkClientVersionResponse * SOAP_FMAC4 soap_new__ns1__checkClientVersionResponse(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__checkClientVersionResponse(struct soap*, const struct _ns1__checkClientVersionResponse *, const char*, const char*);

#ifndef soap_write__ns1__checkClientVersionResponse
#define soap_write__ns1__checkClientVersionResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__ns1__checkClientVersionResponse(soap, data), 0) || soap_put__ns1__checkClientVersionResponse(soap, data, "ns1:checkClientVersionResponse", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT__ns1__checkClientVersionResponse
#define soap_PUT__ns1__checkClientVersionResponse(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize__ns1__checkClientVersionResponse(soap, data), 0) || soap_put__ns1__checkClientVersionResponse(soap, data, "ns1:checkClientVersionResponse", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH__ns1__checkClientVersionResponse
#define soap_PATCH__ns1__checkClientVersionResponse(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize__ns1__checkClientVersionResponse(soap, data), 0) || soap_put__ns1__checkClientVersionResponse(soap, data, "ns1:checkClientVersionResponse", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send__ns1__checkClientVersionResponse
#define soap_POST_send__ns1__checkClientVersionResponse(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize__ns1__checkClientVersionResponse(soap, data), 0) || soap_put__ns1__checkClientVersionResponse(soap, data, "ns1:checkClientVersionResponse", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _ns1__checkClientVersionResponse * SOAP_FMAC4 soap_get__ns1__checkClientVersionResponse(struct soap*, struct _ns1__checkClientVersionResponse *, const char*, const char*);

#ifndef soap_read__ns1__checkClientVersionResponse
#define soap_read__ns1__checkClientVersionResponse(soap, data) ( ((data) ? (soap_default__ns1__checkClientVersionResponse(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get__ns1__checkClientVersionResponse(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET__ns1__checkClientVersionResponse
#define soap_GET__ns1__checkClientVersionResponse(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read__ns1__checkClientVersionResponse(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv__ns1__checkClientVersionResponse
#define soap_POST_recv__ns1__checkClientVersionResponse(soap, data) ( soap_read__ns1__checkClientVersionResponse(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE__ns1__checkClientVersion_DEFINED
#define SOAP_TYPE__ns1__checkClientVersion_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__checkClientVersion(struct soap*, struct _ns1__checkClientVersion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__checkClientVersion(struct soap*, const struct _ns1__checkClientVersion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__checkClientVersion(struct soap*, const char*, int, const struct _ns1__checkClientVersion *, const char*);
SOAP_FMAC3 struct _ns1__checkClientVersion * SOAP_FMAC4 soap_in__ns1__checkClientVersion(struct soap*, const char*, struct _ns1__checkClientVersion *, const char*);

SOAP_FMAC3 struct _ns1__checkClientVersion * SOAP_FMAC4 soap_new__ns1__checkClientVersion(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__checkClientVersion(struct soap*, const struct _ns1__checkClientVersion *, const char*, const char*);

#ifndef soap_write__ns1__checkClientVersion
#define soap_write__ns1__checkClientVersion(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__ns1__checkClientVersion(soap, data), 0) || soap_put__ns1__checkClientVersion(soap, data, "ns1:checkClientVersion", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT__ns1__checkClientVersion
#define soap_PUT__ns1__checkClientVersion(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize__ns1__checkClientVersion(soap, data), 0) || soap_put__ns1__checkClientVersion(soap, data, "ns1:checkClientVersion", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH__ns1__checkClientVersion
#define soap_PATCH__ns1__checkClientVersion(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize__ns1__checkClientVersion(soap, data), 0) || soap_put__ns1__checkClientVersion(soap, data, "ns1:checkClientVersion", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send__ns1__checkClientVersion
#define soap_POST_send__ns1__checkClientVersion(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize__ns1__checkClientVersion(soap, data), 0) || soap_put__ns1__checkClientVersion(soap, data, "ns1:checkClientVersion", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _ns1__checkClientVersion * SOAP_FMAC4 soap_get__ns1__checkClientVersion(struct soap*, struct _ns1__checkClientVersion *, const char*, const char*);

#ifndef soap_read__ns1__checkClientVersion
#define soap_read__ns1__checkClientVersion(soap, data) ( ((data) ? (soap_default__ns1__checkClientVersion(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get__ns1__checkClientVersion(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET__ns1__checkClientVersion
#define soap_GET__ns1__checkClientVersion(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read__ns1__checkClientVersion(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv__ns1__checkClientVersion
#define soap_POST_recv__ns1__checkClientVersion(soap, data) ( soap_read__ns1__checkClientVersion(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns1__stPartInfo_DEFINED
#define SOAP_TYPE_ns1__stPartInfo_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__stPartInfo(struct soap*, struct ns1__stPartInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__stPartInfo(struct soap*, const struct ns1__stPartInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__stPartInfo(struct soap*, const char*, int, const struct ns1__stPartInfo *, const char*);
SOAP_FMAC3 struct ns1__stPartInfo * SOAP_FMAC4 soap_in_ns1__stPartInfo(struct soap*, const char*, struct ns1__stPartInfo *, const char*);

SOAP_FMAC3 struct ns1__stPartInfo * SOAP_FMAC4 soap_new_ns1__stPartInfo(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__stPartInfo(struct soap*, const struct ns1__stPartInfo *, const char*, const char*);

#ifndef soap_write_ns1__stPartInfo
#define soap_write_ns1__stPartInfo(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__stPartInfo(soap, data), 0) || soap_put_ns1__stPartInfo(soap, data, "ns1:stPartInfo", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT_ns1__stPartInfo
#define soap_PUT_ns1__stPartInfo(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_ns1__stPartInfo(soap, data), 0) || soap_put_ns1__stPartInfo(soap, data, "ns1:stPartInfo", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH_ns1__stPartInfo
#define soap_PATCH_ns1__stPartInfo(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_ns1__stPartInfo(soap, data), 0) || soap_put_ns1__stPartInfo(soap, data, "ns1:stPartInfo", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send_ns1__stPartInfo
#define soap_POST_send_ns1__stPartInfo(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_ns1__stPartInfo(soap, data), 0) || soap_put_ns1__stPartInfo(soap, data, "ns1:stPartInfo", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__stPartInfo * SOAP_FMAC4 soap_get_ns1__stPartInfo(struct soap*, struct ns1__stPartInfo *, const char*, const char*);

#ifndef soap_read_ns1__stPartInfo
#define soap_read_ns1__stPartInfo(soap, data) ( ((data) ? (soap_default_ns1__stPartInfo(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns1__stPartInfo(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET_ns1__stPartInfo
#define soap_GET_ns1__stPartInfo(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read_ns1__stPartInfo(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv_ns1__stPartInfo
#define soap_POST_recv_ns1__stPartInfo(soap, data) ( soap_read_ns1__stPartInfo(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_xsd__base64Binary_DEFINED
#define SOAP_TYPE_xsd__base64Binary_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__base64Binary(struct soap*, struct xsd__base64Binary *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__base64Binary(struct soap*, const struct xsd__base64Binary *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const struct xsd__base64Binary *, const char*);
SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__base64Binary2s(struct soap*, struct xsd__base64Binary);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary *, const char*);
SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary *);

SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_new_xsd__base64Binary(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__base64Binary(struct soap*, const struct xsd__base64Binary *, const char*, const char*);

#ifndef soap_write_xsd__base64Binary
#define soap_write_xsd__base64Binary(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_xsd__base64Binary(soap, data), 0) || soap_put_xsd__base64Binary(soap, data, "xsd:base64Binary", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT_xsd__base64Binary
#define soap_PUT_xsd__base64Binary(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_xsd__base64Binary(soap, data), 0) || soap_put_xsd__base64Binary(soap, data, "xsd:base64Binary", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH_xsd__base64Binary
#define soap_PATCH_xsd__base64Binary(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_xsd__base64Binary(soap, data), 0) || soap_put_xsd__base64Binary(soap, data, "xsd:base64Binary", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send_xsd__base64Binary
#define soap_POST_send_xsd__base64Binary(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (soap_serialize_xsd__base64Binary(soap, data), 0) || soap_put_xsd__base64Binary(soap, data, "xsd:base64Binary", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, struct xsd__base64Binary *, const char*, const char*);

#ifndef soap_read_xsd__base64Binary
#define soap_read_xsd__base64Binary(soap, data) ( ((data) ? (soap_default_xsd__base64Binary(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_xsd__base64Binary(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET_xsd__base64Binary
#define soap_GET_xsd__base64Binary(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read_xsd__base64Binary(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv_xsd__base64Binary
#define soap_POST_recv_xsd__base64Binary(soap, data) ( soap_read_xsd__base64Binary(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Reason_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Detail_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Code_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
#endif

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__serveFilePartResponse_DEFINED
#define SOAP_TYPE_PointerTo_ns1__serveFilePartResponse_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__serveFilePartResponse(struct soap*, struct _ns1__serveFilePartResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__serveFilePartResponse(struct soap*, const char *, int, struct _ns1__serveFilePartResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__serveFilePartResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__serveFilePartResponse(struct soap*, const char*, struct _ns1__serveFilePartResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__serveFilePartResponse(struct soap*, struct _ns1__serveFilePartResponse *const*, const char*, const char*);
SOAP_FMAC3 struct _ns1__serveFilePartResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__serveFilePartResponse(struct soap*, struct _ns1__serveFilePartResponse **, const char*, const char*);
#endif

#ifndef SOAP_TYPE_PointerTo_ns1__serveFilePart_DEFINED
#define SOAP_TYPE_PointerTo_ns1__serveFilePart_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__serveFilePart(struct soap*, struct _ns1__serveFilePart *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__serveFilePart(struct soap*, const char *, int, struct _ns1__serveFilePart *const*, const char *);
SOAP_FMAC3 struct _ns1__serveFilePart ** SOAP_FMAC4 soap_in_PointerTo_ns1__serveFilePart(struct soap*, const char*, struct _ns1__serveFilePart **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__serveFilePart(struct soap*, struct _ns1__serveFilePart *const*, const char*, const char*);
SOAP_FMAC3 struct _ns1__serveFilePart ** SOAP_FMAC4 soap_get_PointerTo_ns1__serveFilePart(struct soap*, struct _ns1__serveFilePart **, const char*, const char*);
#endif

#ifndef SOAP_TYPE_PointerTo_ns1__checkClientVersionResponse_DEFINED
#define SOAP_TYPE_PointerTo_ns1__checkClientVersionResponse_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__checkClientVersionResponse(struct soap*, struct _ns1__checkClientVersionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__checkClientVersionResponse(struct soap*, const char *, int, struct _ns1__checkClientVersionResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__checkClientVersionResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__checkClientVersionResponse(struct soap*, const char*, struct _ns1__checkClientVersionResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__checkClientVersionResponse(struct soap*, struct _ns1__checkClientVersionResponse *const*, const char*, const char*);
SOAP_FMAC3 struct _ns1__checkClientVersionResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__checkClientVersionResponse(struct soap*, struct _ns1__checkClientVersionResponse **, const char*, const char*);
#endif

#ifndef SOAP_TYPE_PointerTo_ns1__checkClientVersion_DEFINED
#define SOAP_TYPE_PointerTo_ns1__checkClientVersion_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__checkClientVersion(struct soap*, struct _ns1__checkClientVersion *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__checkClientVersion(struct soap*, const char *, int, struct _ns1__checkClientVersion *const*, const char *);
SOAP_FMAC3 struct _ns1__checkClientVersion ** SOAP_FMAC4 soap_in_PointerTo_ns1__checkClientVersion(struct soap*, const char*, struct _ns1__checkClientVersion **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__checkClientVersion(struct soap*, struct _ns1__checkClientVersion *const*, const char*, const char*);
SOAP_FMAC3 struct _ns1__checkClientVersion ** SOAP_FMAC4 soap_get_PointerTo_ns1__checkClientVersion(struct soap*, struct _ns1__checkClientVersion **, const char*, const char*);
#endif

#ifndef SOAP_TYPE_PointerTons1__stPartInfo_DEFINED
#define SOAP_TYPE_PointerTons1__stPartInfo_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__stPartInfo(struct soap*, struct ns1__stPartInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__stPartInfo(struct soap*, const char *, int, struct ns1__stPartInfo *const*, const char *);
SOAP_FMAC3 struct ns1__stPartInfo ** SOAP_FMAC4 soap_in_PointerTons1__stPartInfo(struct soap*, const char*, struct ns1__stPartInfo **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__stPartInfo(struct soap*, struct ns1__stPartInfo *const*, const char*, const char*);
SOAP_FMAC3 struct ns1__stPartInfo ** SOAP_FMAC4 soap_get_PointerTons1__stPartInfo(struct soap*, struct ns1__stPartInfo **, const char*, const char*);
#endif

#ifndef SOAP_TYPE_PointerTounsignedByte_DEFINED
#define SOAP_TYPE_PointerTounsignedByte_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
#endif

#ifndef SOAP_TYPE__QName_DEFINED
#define SOAP_TYPE__QName_DEFINED

#ifdef SOAP_DEFAULT__QName
#define soap_default__QName(soap, a) (*(a) = SOAP_DEFAULT__QName)
#else
#define soap_default__QName(soap, a) (*(a) = (char *)0)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);

#define soap__QName2s(soap, a) soap_QName2s(soap, (a))
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);

#define soap_s2_QName(soap, s, a) soap_s2QName((soap), (s), (char**)(a), 0, -1, NULL)
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
#define soap_new__QName soap_new_string

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || soap_put__QName(soap, data, "QName", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT__QName
#define soap_PUT__QName(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put__QName(soap, data, "QName", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH__QName
#define soap_PATCH__QName(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put__QName(soap, data, "QName", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send__QName
#define soap_POST_send__QName(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put__QName(soap, data, "QName", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET__QName
#define soap_GET__QName(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read__QName(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv__QName
#define soap_POST_recv__QName(soap, data) ( soap_read__QName(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE__XML_DEFINED
#define SOAP_TYPE__XML_DEFINED
#endif

#ifndef SOAP_TYPE_string_DEFINED
#define SOAP_TYPE_string_DEFINED

#ifdef SOAP_DEFAULT_string
#define soap_default_string(soap, a) (*(a) = SOAP_DEFAULT_string)
#else
#define soap_default_string(soap, a) (*(a) = (char *)0)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);

#define soap_string2s(soap, a) (a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);

#define soap_s2string(soap, s, a) soap_s2char((soap), (s), (char**)(a), 1, 0, -1, NULL)
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

SOAP_FMAC3 char * * SOAP_FMAC4 soap_new_string(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || soap_put_string(soap, data, "string", "") || soap_end_send(soap), (soap)->error )
#endif


#ifndef soap_PUT_string
#define soap_PUT_string(soap, URL, data) ( soap_free_temp(soap), soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_string(soap, data, "string", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_PATCH_string
#define soap_PATCH_string(soap, URL, data) ( soap_free_temp(soap), soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_string(soap, data, "string", "") || soap_end_send(soap) || soap_recv_empty_response(soap), soap_closesock(soap) )
#endif


#ifndef soap_POST_send_string
#define soap_POST_send_string(soap, URL, data) ( soap_free_temp(soap), ( soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || soap_put_string(soap, data, "string", "") || soap_end_send(soap) ) && soap_closesock(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef soap_GET_string
#define soap_GET_string(soap, URL, data) ( soap_GET(soap, URL, NULL) || soap_read_string(soap, (data)), soap_closesock(soap) )
#endif


#ifndef soap_POST_recv_string
#define soap_POST_recv_string(soap, data) ( soap_read_string(soap, (data)) || soap_closesock(soap), (soap)->error )
#endif

#endif

#endif

/* End of soapH.h */
