/* soapClient.c
   Generated by gSOAP 2.8.119 for bfsrv.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.119 2022-02-15 21:52:35 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__checkClientVersion(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__checkClientVersion *ns1__checkClientVersion, struct _ns1__checkClientVersionResponse *ns1__checkClientVersionResponse)
{	if (soap_send___ns1__checkClientVersion(soap, soap_endpoint, soap_action, ns1__checkClientVersion) || soap_recv___ns1__checkClientVersion(soap, ns1__checkClientVersionResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__checkClientVersion(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__checkClientVersion *ns1__checkClientVersion)
{	struct __ns1__checkClientVersion soap_tmp___ns1__checkClientVersion;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://onsite.it-solutions.atos.net/BFService/serveBFService.asmx";
	if (soap_action == NULL)
		soap_action = "http://onsite.it-solutions.atos.net/webservices/checkClientVersion";
	soap_tmp___ns1__checkClientVersion.ns1__checkClientVersion = ns1__checkClientVersion;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__checkClientVersion(soap, &soap_tmp___ns1__checkClientVersion);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__checkClientVersion(soap, &soap_tmp___ns1__checkClientVersion, "-ns1:checkClientVersion", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__checkClientVersion(soap, &soap_tmp___ns1__checkClientVersion, "-ns1:checkClientVersion", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__checkClientVersion(struct soap *soap, struct _ns1__checkClientVersionResponse *ns1__checkClientVersionResponse)
{
	if (!ns1__checkClientVersionResponse)
		return soap_closesock(soap);
	soap_default__ns1__checkClientVersionResponse(soap, ns1__checkClientVersionResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__checkClientVersionResponse(soap, ns1__checkClientVersionResponse, "ns1:checkClientVersionResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__serveFilePart(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__serveFilePart *ns1__serveFilePart, struct _ns1__serveFilePartResponse *ns1__serveFilePartResponse)
{	if (soap_send___ns1__serveFilePart(soap, soap_endpoint, soap_action, ns1__serveFilePart) || soap_recv___ns1__serveFilePart(soap, ns1__serveFilePartResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__serveFilePart(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__serveFilePart *ns1__serveFilePart)
{	struct __ns1__serveFilePart soap_tmp___ns1__serveFilePart;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://onsite.it-solutions.atos.net/BFService/serveBFService.asmx";
	if (soap_action == NULL)
		soap_action = "http://onsite.it-solutions.atos.net/webservices/serveFilePart";
	soap_tmp___ns1__serveFilePart.ns1__serveFilePart = ns1__serveFilePart;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__serveFilePart(soap, &soap_tmp___ns1__serveFilePart);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__serveFilePart(soap, &soap_tmp___ns1__serveFilePart, "-ns1:serveFilePart", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__serveFilePart(soap, &soap_tmp___ns1__serveFilePart, "-ns1:serveFilePart", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__serveFilePart(struct soap *soap, struct _ns1__serveFilePartResponse *ns1__serveFilePartResponse)
{
	if (!ns1__serveFilePartResponse)
		return soap_closesock(soap);
	soap_default__ns1__serveFilePartResponse(soap, ns1__serveFilePartResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__serveFilePartResponse(soap, ns1__serveFilePartResponse, "ns1:serveFilePartResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__checkClientVersion_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__checkClientVersion *ns1__checkClientVersion, struct _ns1__checkClientVersionResponse *ns1__checkClientVersionResponse)
{	if (soap_send___ns1__checkClientVersion_(soap, soap_endpoint, soap_action, ns1__checkClientVersion) || soap_recv___ns1__checkClientVersion_(soap, ns1__checkClientVersionResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__checkClientVersion_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__checkClientVersion *ns1__checkClientVersion)
{	struct __ns1__checkClientVersion_ soap_tmp___ns1__checkClientVersion_;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://onsite.it-solutions.atos.net/BFService/serveBFService.asmx";
	if (soap_action == NULL)
		soap_action = "http://onsite.it-solutions.atos.net/webservices/checkClientVersion";
	soap_tmp___ns1__checkClientVersion_.ns1__checkClientVersion = ns1__checkClientVersion;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__checkClientVersion_(soap, &soap_tmp___ns1__checkClientVersion_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__checkClientVersion_(soap, &soap_tmp___ns1__checkClientVersion_, "-ns1:checkClientVersion", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__checkClientVersion_(soap, &soap_tmp___ns1__checkClientVersion_, "-ns1:checkClientVersion", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__checkClientVersion_(struct soap *soap, struct _ns1__checkClientVersionResponse *ns1__checkClientVersionResponse)
{
	if (!ns1__checkClientVersionResponse)
		return soap_closesock(soap);
	soap_default__ns1__checkClientVersionResponse(soap, ns1__checkClientVersionResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__checkClientVersionResponse(soap, ns1__checkClientVersionResponse, "ns1:checkClientVersionResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__serveFilePart_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__serveFilePart *ns1__serveFilePart, struct _ns1__serveFilePartResponse *ns1__serveFilePartResponse)
{	if (soap_send___ns1__serveFilePart_(soap, soap_endpoint, soap_action, ns1__serveFilePart) || soap_recv___ns1__serveFilePart_(soap, ns1__serveFilePartResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__serveFilePart_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__serveFilePart *ns1__serveFilePart)
{	struct __ns1__serveFilePart_ soap_tmp___ns1__serveFilePart_;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://onsite.it-solutions.atos.net/BFService/serveBFService.asmx";
	if (soap_action == NULL)
		soap_action = "http://onsite.it-solutions.atos.net/webservices/serveFilePart";
	soap_tmp___ns1__serveFilePart_.ns1__serveFilePart = ns1__serveFilePart;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__serveFilePart_(soap, &soap_tmp___ns1__serveFilePart_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__serveFilePart_(soap, &soap_tmp___ns1__serveFilePart_, "-ns1:serveFilePart", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__serveFilePart_(soap, &soap_tmp___ns1__serveFilePart_, "-ns1:serveFilePart", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__serveFilePart_(struct soap *soap, struct _ns1__serveFilePartResponse *ns1__serveFilePartResponse)
{
	if (!ns1__serveFilePartResponse)
		return soap_closesock(soap);
	soap_default__ns1__serveFilePartResponse(soap, ns1__serveFilePartResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__serveFilePartResponse(soap, ns1__serveFilePartResponse, "ns1:serveFilePartResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
